### ISSUE TITLE
requests

### ISSUE THREAD

**Issue by gsgoldma** [mix1009/model-keyword#10]
can there be included a way to add keywords inside auto1111, without going to the user script?
can there be a menu that drops down that tells you all the keywords associated with the model before you generate? 
thank you

**Comment by mix1009** [comment]
Now it's possible to add custom mapping from the UI. Thank you for the suggestion.
Displaying associated keywords is not currently supported. I'll think about it.

**Comment by mix1009** [comment]
There is a "Check", "Save", "Delete" button inside "Add Custom Mappings" section.
"Check" displays matching keywords.

Thank you for the feature request :)

**Comment by gsgoldma** [comment]
sorry again, i can't find the add the  add custom mappings section

**Comment by gsgoldma** [comment]
my extension wasn't updating. I see it now. thank you for adding it.
