### ISSUE TITLE
model-keyword-user.txt overwritten on updates

### ISSUE THREAD

**Issue by Kilvoctu** [mix1009/model-keyword#12]
Hi, 
Whenever this extension is updated through Web UI, the model-keyword-user.txt is overwritten back to the default file. 
I'm not sure how Web UI updates extensions, but please consider how this file is handled, so it doesn't get overwritten each update.

**Comment by mix1009** [comment]
Thank you for the bug report.

You are right! I'm not sure why it's being overwritten, but it is.
I'll fix it :)

Thanks again.

**Comment by Kilvoctu** [comment]
Yeah, it seems like it shouldn't since it's added to .gitignore. However, the issue happened a few times already reliably, so I figured it was no fluke occurence.
Thanks for looking into it 👍

**Comment by iarna** [comment]
Having the file in .gitignore doesn't matter if it's checked into the repo. I would suggest having `model_keyword.py` generate the file (if missing) when it starts up. (And then remove it from the repo.)

**Comment by mix1009** [comment]
Now the extension uses user-mappings.txt instead of model-keyword-user.txt .
Please use the UI to add mappings now. (The hash algorithm changed in webui, and old hash value is no longer displayed)

**Comment by Kilvoctu** [comment]
Excellent, this will do nicely! Thanks for the quick solution 👍👍
