### ISSUE TITLE
Can't handle more than two keywords

### ISSUE THREAD

**Issue by alfonslm** [mix1009/model-keyword#14]
The current interface can't handle more than two keywords and ie. SynthPunk V.3 (https://civitai.com/models/2856/synthpunk-search) uses 3 keywords.
I would probably solve it by using checkboxes and ordering them from an input number next to them or by having a drag and drop list with keywords at the start, end and inactive.

**Comment by mix1009** [comment]
Extension only runs when you generate an image, or interact with the extension UI.
I don't think it's possible to update the UI according to the current selected model.
I could add 'keyword3', 'keyword4' ... etc. would it help?

**Comment by alfonslm** [comment]
Could you do something like `foreach(keyword){print "keywordname" + selectionboxN}` and add an update button that you press when you change diffusion model since using a hardcoded list will probably always have the wrong number of options in this case.

**Comment by mix1009** [comment]
I'll check if it's possible to change the dropdown list when a button is pressed.
But if user doesn't press the button it will not update and will confuse users more IMO.

You can see the keyword list by clicking "Check" button in 'Add Custom Mappings' section.
I think adding 'keyword3', 'keyword4', 'keyword5' is the second best way to solve the problem.
If there is no keywordX, it will default to keyword1.

**Comment by alfonslm** [comment]
If there is a button that says "Update keyword for new model" at the top it is hopefully good enough for most

**Comment by mix1009** [comment]
Refresh button for Multiple keywords has been implemented :)

<img width="802" alt="스크린샷 2023-01-17 오후 11 06 42" src="https://user-images.githubusercontent.com/1288793/212920377-d6df8b1d-7128-476e-9e94-06bf34724a26.png">

Button placement is a bit off. It's not easy to control using gradio components.

Thank you for the request.

**Comment by alfonslm** [comment]
So, this is only relevant since you got it working but what do you feel about adding a persistent list probably mostly for "Textual Inversion"

**Comment by mix1009** [comment]
Interesting!
Should it be included in this extension? Or maybe a new extension?

**Comment by alfonslm** [comment]
Not sure if it would be beneficial to have a second extension with some code removed with more or less the same usage.
You don't need to use get_old_model_hash or do all of the elif since only the multiple_keywords condition is relevant for the keywords, at least sort of.
It might be easier to try and optimize the code for the keywords also since they don't need any extra steps.

I guess that default settings per model could be the next step since some got keywords that is optional eg Arts and Eros list (ELDEN RING STYLE, MODELSHOOT STYLE, DREAMLIKEART, POSTAPOCALYPSE, ANALOG STYLEK, NOLLINGCASE, SWPUNK, SYNTHWAVE, CYBORGDIFFUSION)

**Comment by mix1009** [comment]
If I add "textual inversion" dropdown separately to this extension, how should I order the keywords?

model_keyword ti_keyword
or
ti_keyword model_keyword

Should that be an option?

**Comment by alfonslm** [comment]
I guess ti_keyword makes more sense first if model_keyword will get a default setting. Otherwise it probably don't mater all that much

**Comment by alfonslm** [comment]
Right, model and textural inversion keyword should probably have a switch for what order it would be added. `Model, Textural Inversion` or `Textural Inversion, Model`

**Comment by mix1009** [comment]
Textual Inversion is now implemented!
