### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by edgardmello** [mix1009/model-keyword#16]
Is there an existing issue for this?
I have searched the existing issues and checked the recent builds/commits, but I couldn't find a similar issue.

What happened?
I am getting the following error when running the process: C:\sd\webui\extensions\model-keyword\scripts\model_keyword.py

Traceback (most recent call last):
File "C:\sd\webui\modules\scripts.py", line 347, in process
script.process(p, *script_args)
File "C:\sd\webui\extensions\model-keyword\scripts\model_keyword.py", line 327, in process
kw = self.get_keyword(model_hash, model_ckpt)
File "C:\sd\webui\extensions\model-keyword\scripts\model_keyword.py", line 243, in get_keyword
hash_dict = self.load_hash_dict()
File "C:\sd\webui\extensions\model-keyword\scripts\model_keyword.py", line 213, in load_hash_dict
modified = str(os.stat(default_file).st_mtime) + '_' + str(os.stat(user_file).st_mtime)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\sd\webui\extensions\model-keyword/custom-mappings.txt'

Steps to reproduce the problem

Run the process "C:\sd\webui\extensions\model-keyword\scripts\model_keyword.py"
What should have happened?

The process should have run without any errors.
Commit where the problem happens

My Webui is on Commit hash a8322ad.

What platforms do you use to access UI ?
Windows

What browsers do you use to access the UI ?
Google Chrome

Command Line Arguments
None

Additional information, context and logs
none

Thank you.

**Comment by mix1009** [comment]
Thank you for the detailed bug report. That was a bug when custom-mappings.txt file does not exist.
Latest version will make the file if it does not exist.

**Comment by edgardmello** [comment]
Btw, this extension is awesome.

**Comment by mix1009** [comment]
I think @iarna is working on an implementation.

**Comment by mix1009** [comment]
The bug reappeared with the new update, and was fixed again.

For saving settings, I'll follow up in #17 .
