### ISSUE TITLE
Is it possible to save settings?

### ISSUE THREAD

**Issue by an303042** [mix1009/model-keyword#17]
Right now I need to change "Multiple keywords:" to random (or whatever I want) every time I start the ui. I would prefer it to save my preferred setting.
I've looked through the settings but couldn't find an option for it. Sorry if it's just me being blind

**Comment by mix1009** [comment]
There is no settings save feature.
I'll check what's the best practice for saving settings in webui extensions.

Thank you for the report.

**Comment by mix1009** [comment]
settings are now saved. They are saved when an image is generated.

settings are saved in settings.txt:
```
is_enabled=True
keyword_placement=keyword prompt
multiple_keywords=keyword1, keyword2
ti_keywords=None
keyword_order=textual inversion first
```
