### ISSUE TITLE
README - I had to use a different path to install the extension in Automatic1111

### ISSUE THREAD

**Issue by ejrejr** [mix1009/model-keyword#19]
I tried to install the extension given the README directions but I got a git error via A1111 when trying to do so (I have git bash installed and it is accessible through the PATH).

FWIW, I did install by giving the GitHub clone path to A1111:
https://github.com/mix1009/model-keyword.git

I restarted the UI and the extension is installed.

This is on Windows 10.

Command line output:
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v  https://github.com/mix1009/model-keyword  C:\Users\Eric\repos\Stable-Diffusion\stable-diffusion-webui\tmp\model-keyword
  stderr: 'fatal: could not create work tree dir 'C:\Users\Eric\repos\Stable-Diffusion\stable-diffusion-webui\tmp\model-keyword ': Invalid argument

**Comment by iarna** [comment]
Personally, I installed it via the the extension browser, but I don't see how that'd make a difference.  Have you tried running that git command stand alone? 

This is what I see:

```console
> git clone -v https://github.com/mix1009/model-keyword C:\Users\Rebecca\repos\Stable-Diffusion\stable-diffusion-webui\tmp\model-keyword
Cloning into 'C:\Users\Rebecca\repos\Stable-Diffusion\stable-diffusion-webui\tmp\model-keyword'...
POST git-upload-pack (185 bytes)
POST git-upload-pack (212 bytes)
remote: Enumerating objects: 481, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 481 (delta 25), reused 25 (delta 13), pack-reused 441
Receiving objects: 100% (481/481), 82.73 KiB | 1.43 MiB/s, done.
Resolving deltas: 100% (296/296), done.
```

via git bash:
```console
$ git clone -v https://github.com/mix1009/model-keyword 'C:\Users\Rebecca\repos\Stable-Diffusion\stable-diffusion-webui\tmp\model-keyword'
Cloning into 'C:\Users\Rebecca\repos\Stable-Diffusion\stable-diffusion-webui\tmp\model-keyword'...
POST git-upload-pack (185 bytes)
POST git-upload-pack (212 bytes)
remote: Enumerating objects: 481, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 481 (delta 25), reused 25 (delta 13), pack-reused 441
Receiving objects: 100% (481/481), 82.73 KiB | 1.62 MiB/s, done.
Resolving deltas: 100% (296/296), done.
```

and just for funsies, with wsl:
```console
> wsl git clone -v https://github.com/mix1009/model-keyword C:\Users\Rebecca\repos\Stable-Diffusion\stable-diffusion-webui\tmp\model-keyword
Cloning into '/mnt/c/Users/Rebecca/repos/Stable-Diffusion/stable-diffusion-webui/tmp/model-keyword'...
POST git-upload-pack (164 bytes)
POST git-upload-pack (202 bytes)
remote: Enumerating objects: 481, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 481 (delta 25), reused 25 (delta 13), pack-reused 441
Receiving objects: 100% (481/481), 82.73 KiB | 1.69 MiB/s, done.
Resolving deltas: 100% (296/296), done.
```

**Comment by ejrejr** [comment]
Hi. Yes that command line above works when I go to my git bash, putting it into some tmp directory. I didn't want to goof around doing a manual extension install (not sure if that /tmp/ should actually be the /extensions/ directory), so I was happier to do so via the Extensions tab in A1111. While the current given path in the README didn't work in my recent A1111 pull, the .git path did and the extension is installed.

Just sharing my varied mileage. Cheers.

**Comment by mix1009** [comment]
I tried installing using 3 methods
1. Extension - Install from URL: https://github.com/mix1009/model-keyword 
2. Extension - Install from URL: https://github.com/mix1009/model-keyword.git
3. Extension - Available - Load from method

It worked on my Windows 10 installation with the latest webui
and git(64bit Windows setup with default settings) from https://git-scm.com/download/win .

**Comment by ejrejr** [comment]
Totally fine to close if I'm a one-off. I have my work-around - I'm not sure why it barfed for me. Looks like our setup is pretty much the same. Cheers.
