### ISSUE TITLE
Integration with Plot X/Y?

### ISSUE THREAD

**Issue by system1system2** [mix1009/model-keyword#2]
This is a great extension that will save me tons of time. Thanks for sharing it with the community.

Is there any chance to integrate it, somehow, with the Plot X/Y script?

Plot X/Y already allows to call different checkpoints/models but there's no way to automatically include the relevant keyword for each checkpoint in the prompt.

If these two extensions could work together, it would be amazing.

**Comment by mix1009** [comment]
I'll need some time to see if it's possible. It's a great idea!

**Comment by mix1009** [comment]
Tested it, and it already works!

<img width="1457" alt="Screenshot 2022-12-28 at 10 08 25 AM" src="https://user-images.githubusercontent.com/1288793/209742120-728404d5-8dc8-4e8b-a8df-19847cb09d08.png">
