### ISSUE TITLE
Message settings2 with each generated image

### ISSUE THREAD

**Issue by cjps-br** [mix1009/model-keyword#21]
I updated the extension version today (January 31, 2023) and a message started to appear with each generated image:
settings2 = {'is_enabled': 'True', 'keyword_placement': 'keyword prompt', 'multiple_keywords': 'keyword1, keyword2', 'ti_keywords': 'None', 'keyword_order': 'textual inversion first'}

**Comment by mix1009** [comment]
I'll delete the log on the next code update.
Thank you for report.
