### ISSUE TITLE
[Feature Request] Lora support?

### ISSUE THREAD

**Issue by scruffynerf** [mix1009/model-keyword#24]
With Loras gaining massive speed (and small size), they are growing in popularity.  Mostly similar to the checkpoint models, they use trigger words...  so a hash/trigger word approach would be needed.  Pretty much like a middle ground between TIs and Checkpoint models.

Loras only get loaded on prompt start, so either adding them via model keyword (similar to TIs), or detecting they are in prompt as <lora:Lorafilename:1> (# is strength, can be floating and more or less than 1)

**Comment by gitpulled** [comment]
This would be amazing. Could we get this to be a thing? I download Loras and have to keep referencing outside sources from the gui.

**Comment by axsddlr** [comment]
this would be revolutionary

**Comment by mix1009** [comment]
How are you using Lora models? Is it natively supported in webui or do we still need https://github.com/kohya-ss/sd-webui-additional-networks ?

**Comment by mix1009** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#lora

Looks like it's natively supported :)

**Comment by scruffynerf** [comment]
[lorahashtriggerlist.txt](https://github.com/mix1009/model-keyword/files/10777629/lorahashtriggerlist.txt)

Here's a jumpstart... hashes v1, trigger, and lora filename...  sourced from Civitai json records.
Not every lora is there, as some only have hashv2

**Comment by mix1009** [comment]
> 

How did you get nsfw contents? The REST API for models only returns nsfw=False without the api key. Could not find any documentation on how to use the api key for REST API.

**Comment by scruffynerf** [comment]
Most of that is sourced before apikey was added.

We have a script that should work, and I'll get @justmaier of Civitai involved if need be.

**Comment by mix1009** [comment]
> 

That would be great. I'm running cron scripts to update the text file.

**Comment by mix1009** [comment]
Implemented LORA support. Default database doesn't contain NSFW, but users can add custom mappings.

**Comment by mix1009** [comment]
About the AutoV1 hash problem. AutoV1 hashes 64KB starting from 1MB.
Even though some hashes are missing from the civitai json, it's really easy to calculate hash without downloading the whole model file.
But some LORA models are smaller than 1MB. I'll try to hash the whole file in this case.
The workaround shouldn't have side effects since nobody seems to use it now :>

**Comment by scruffynerf** [comment]
There are hash v2s in Civitai, I just didn't include them because you were not using them.  Easily added.

**Comment by scruffynerf** [comment]
> That would be great. I'm running cron scripts to update the text file.

If you msg me or post the cron job script, I'll review and get it working.  "API key shouldn’t be necessary unless they’re trying to do user specific stuff like getting favorites or downloading an early access model." is the official answer I got.

**Comment by scruffynerf** [comment]
"There was a bug in the api after adding the browsing mode changes yesterday. This should be working as expected again now."  Try it now.  Let me know if you get all of the models you are looking for.

**Comment by mix1009** [comment]
Tried it now, but seems civitai.com is down.
502(cloudflare) for website.
503 for api.

I'll try later. Thanks.

**Comment by mix1009** [comment]
The API is working and it's returning all LORA models including NSFW.

**Comment by scor2** [comment]
I've been testing a new feature, but I have a question.

1. It doesn't recognize Lora in the subfolder.
models\Lora\aaa
In this case, Lora in the aaa folder is not recognized.


2. Keywords are not added when using the basic functions of WEBUI.
![a1](https://user-images.githubusercontent.com/117506473/220726137-1816427b-fb11-4570-b085-1a3afe65e5ba.png)

Do I have to manually select Lora and keywords in the Model-keyword extension?
