### ISSUE TITLE
I have a question about Lora feature

### ISSUE THREAD

**Issue by scor2** [mix1009/model-keyword#25]
1. 
![a11](https://user-images.githubusercontent.com/117506473/221102168-ff920825-c4f7-43ea-bba6-a00ae996e98c.png)

Lora Keywords are not added when I use the Default Lora functions of WEBUI.

Should I manually select Lora and keywords in the Model-keyword extension dropdown menu?

I hope keyword add automatically when I use Default Lora Functions of WEBUI.

2.
![a2](https://user-images.githubusercontent.com/117506473/221101804-981a348c-7823-491d-86b7-26973a289ac2.png)

Extension doesn't recognize Lora in the subfolder.

models\Lora\Vehcile

In this case, Lora in the Vehicle folder doesn't recognized in Model-Keyword Extension.

**Comment by mix1009** [comment]
Thank you. I've updated the extension to support LORA models in sub folders.

**Comment by mix1009** [comment]
Thank you for the bug report. I fixed the bug!
