### ISSUE TITLE
[Feature Request] Can Lora models dropdown be ordered alphabetically?

### ISSUE THREAD

**Issue by edgardmello** [mix1009/model-keyword#29]
See the example below.

None
anime_nausicae.safetensors
artist_dan_mumford.safetensors
illustration_kSUWABESTYLE_v2.safetensors
illustration_enaic.safetensors
special_epiNoiseoffset_v2.safetensors
special_offset.safetensors
style_anaglyph.safetensors
style_rotoscopee.safetensors

I organize the Loras with types before their names.

**Comment by mix1009** [comment]
Please check the latest version :)

50d53d836dd8f463dc2c447594c82a0ffffd4390

**Comment by edgardmello** [comment]
You nailed it! Can it be the same for Textual Inversion (Embedding) 😁
