### ISSUE TITLE
[Feature Request] Embedding Trigger words

### ISSUE THREAD

**Issue by ataa** [mix1009/model-keyword#3]
Thank you for sharing this extension.

It would be great to have the same functionality for Embedding/Textual Inversions keywords and notes.

I hope @Civitai can provide a list of Embedding, trigger words and hashes.

**Comment by mix1009** [comment]
I think you can use the filename without the extension for trigger words in Embeddings folder.
civitai provided "trigger words" for textual embedding seems to be same as the filename downloaded.

If you are downloading from https://huggingface.co/sd-concepts-library, it's a pain.
You'll have to manually rename the file by looking at the token-identifier.txt .

I made a colab to download all the public sd-concept-library embeddings and rename it.
https://colab.research.google.com/drive/1hExbjp69gQ2cEPNs_t0owTNpHEW5Wsjo?usp=sharing

Here's a zip file downloaded a few days ago.
[embeddings.zip](https://github.com/mix1009/model-keyword/files/10305002/embeddings.zip)

**Comment by mix1009** [comment]
I don't think this extension should automatically add keywords for textual inversion. User should choose which embeddings to use.
