### ISSUE TITLE
LyCORIS support

### ISSUE THREAD

**Issue by doodooextinction** [mix1009/model-keyword#32]
Your tool is very useful and I appreciate your work. 
I was just wondering if you were going to add LyCORIS support?
I'm not sure how well these will catch on, but it looks Civitai is getting more and more of them.
https://github.com/KohakuBlueleaf/LyCORIS
https://github.com/KohakuBlueleaf/a1111-sd-webui-locon

**Comment by mix1009** [comment]
LoCon (LyCORIS) models are now being indexed now.
It works same as LORA models and the info is also saved in lora.txt

Thank you for the request.
