### ISSUE TITLE
Comic Diffusion v2 issue with current token

### ISSUE THREAD

**Issue by system1system2** [mix1009/model-keyword#4]
Comic Diffusion v2 [8b3c8f111] is currently with token `comicmay artsyle`. However, per instructions [here](https://huggingface.co/ogkalu/Comic-Diffusion) there are 6 activation token and none of them matches the one currently used:

> charliebo artstyle
> holliemengert artstyle
> marioalberti artstyle
> pepelarraz artstyle
> andreasrocha artstyle
> jamesdaly artstyle

Not sure how you'll implement this :) Ideally, somebody would want to be able to pick which one of the 6 to enforce.

**Comment by mix1009** [comment]
Comic Diffusion v1/v2 should work now. Thank you for the issue report.

# v1
234cc409, comicmay artsyle

# v2
8b3c8f11, charliebo artstyle|holliemengert artstyle|marioalberti artstyle|pepelarraz artstyle|andreasrocha artstyle|jamesdaly artstyle
