### ISSUE TITLE
Add Woolitize model

### ISSUE THREAD

**Issue by system1system2** [mix1009/model-keyword#5]
From https://huggingface.co/plasmo/woolitize

f2ea5e141, woolitize, woolitize768.ckpt

**Comment by mix1009** [comment]
added!

5714e58c, woolitize
97db9b40, woolitize
e1b7c805, woolitize

**Comment by mix1009** [comment]
Where can i get woolitize768.ckpt?
I can only find 3 files:
<img width="1251" alt="Screenshot 2022-12-29 at 11 09 04 PM" src="https://user-images.githubusercontent.com/1288793/209965056-dd8a622c-6380-4fba-9a24-9f064602a8aa.png">

**Comment by mix1009** [comment]
found it! https://huggingface.co/plasmo/woolitize-768sd1-5

**Comment by mix1009** [comment]
updated :)
