### ISSUE TITLE
Correct token for VintageCream model

### ISSUE THREAD

**Issue by system1system2** [mix1009/model-keyword#7]
Currently, the VintageCream model [a5c134f5] has associated the token `naturitize`. However, the correct activation token is `vntgcrm style` according to https://huggingface.co/SebastianKamphYT/VintageCream

**Comment by mix1009** [comment]
there is a hash collision with https://civitai.com/models/2334/jaks-naturitize-image-pack .

I added VintageCream.

a5c134f5, naturitize, jakSNaturitizeImageP_naturitizeSd21768Px.ckpt
a5c134f5, vntgcrm style, VintageCream.ckpt
