### ISSUE TITLE
Multiple keywords modality "Iterate" generates a single image

### ISSUE THREAD

**Issue by system1system2** [mix1009/model-keyword#8]
I'm testing the new Comic Diffusion v2 model with 6 activation tokens. 

I set up the `Multiple Keywords` mode to `Iterate`, as I want A1111 to produce 6 images, one for each activation token. 
As I click Generate, tho, only a single image is produced.

Did I misunderstand the intent of the iterate mode?

**Comment by mix1009** [comment]
When you generate an image, it will use the first keyword.
Next time you generate an image, it will use the next keyword...
The extension doesn't generate multiple prompts from a prompt.

**Comment by mix1009** [comment]
Thanks for the suggestion. I'll test what's possible.
